#!/bin/bash

# Add exceptions to the firewall
echo "Adding CyberLynk Support Network Exception to Firewall"

fwconsole firewall trust 192.159.66.96/27
fwconsole firewall stop
fwconsole firewall start

# Check for authorized_keys
if test -f /root/.ssh/authorized_keys; then
    echo "Creating authorized keys file"
    mkdir /root/.ssh
    touch /root/.ssh/authorized_keys
    echo "Authorized keys file has been created at /root/.ssh/authorized_keys"
fi

# Copy keys
curl https://raw.githubusercontent.com/CyberLynk/freepbxhosting_resources/main/keylist >> /root/.ssh/authorized_keys

# Let the user know what happened
echo "Firewall exception for CyberLynk Support has been created"
echo "CyberLynk ssh keys have been added to your server"
echo "To undo those changes run MYSTERIOUS SCRIPT THAT HAS NOT YET BEEN WRITTEN YET"
